[package]
name = "steam-deck-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ipjail"
path = "src/ipjail.rs"

[dependencies]
anyhow = "1.0.75"
libc = "0.2.147"
